Repository yejin013/Oddok, pull requests merged in 2022-07, with the labels that each got.

#161 [BE] 로그인 에러처리
  server/src/main/java/com/oddok/server/common/errors/SocialDataNotFoundException.java
  server/src/main/java/com/oddok/server/common/jwt/JwtAuthenticationFilter.java
  server/src/main/java/com/oddok/server/domain/user/client/ClientKakao.java
Labels: 🐛FIX

#160 [FE] 스터디룸 참여자 정보 조회
  client/src/assets/icons/award-fill.svg
  client/src/assets/icons/index.js
  client/src/components/study/ParticipantSideBar/ParticipantSideBar.jsx
  client/src/components/study/ParticipantSideBar/ParticipantSideBar.module.css
  client/src/components/study/SettingRoom/SettingRoom.jsx
  client/src/components/study/SettingRoom/SettingRoom.module.css
  client/src/components/study/StudyBar/StudyBar.jsx
  client/src/components/study/StudyBar/StudyBar.module.css
  client/src/components/study/TotalTime/TotalTime.module.css
  client/src/components/study/UserTag/UserTag.jsx
  client/src/components/study/UserTag/UserTag.module.css
  client/src/components/study/UserVideo/UserVideo.jsx
  client/src/components/study/index.js
  client/src/pages/StudyRoom/StudyRoom.jsx
  client/src/pages/StudyRoom/StudyRoom.module.css
Labels: 🎂FEAT

#179 [FE] url 직접 접근 라우터 처리
  client/.eslintrc.json
  client/src/App.jsx
  client/src/components/router/PrivateRoute.jsx
  client/src/components/router/PublicRoute.jsx
  client/src/components/router/index.js
  client/src/pages/JoinRoom.jsx
  client/src/pages/Login/RedirectPage.jsx
  client/src/pages/LogoutRedirectPage/LogoutRedirectPage.jsx
Labels: 🐛FIX

#178 [FE] 전역 에러 모달 추가 및 오류 수정
  client/src/App.jsx
  client/src/api/axios-config.js
  client/src/api/error/ApiError.js
  client/src/api/error/LoginError.js
  client/src/api/error/OpenviduError.js
  client/src/api/error/StudyRoomError.js
  client/src/api/openvidu-api.js
  client/src/api/study-room-api.js
  client/src/components/commons/ErrorModal/ErrorModal.jsx
  client/src/components/commons/Modal/Modal.module.css
  client/src/components/commons/index.js
  client/src/hooks/useAsync.js
  client/src/hooks/useFetch.js
  client/src/pages/CreateRoom.jsx
  client/src/pages/JoinRoom.jsx
  client/src/pages/MyPage/MyPage.jsx
  client/src/pages/StudyRoom/StudyRoom.jsx
  client/src/recoil/error-state.js
  client/src/utils/constants/API_ERROR.js
Labels: 🐛FIX, ♻️REFAC
