Repository yejin013/Oddok, pull requests merged in 2022-08, with the labels that each got.

#180 [FE] 채팅 사이드바 무한 스크롤 구현
  client/src/components/study/ChatSideBar/ChatItem/ChatItem.jsx
  client/src/components/study/ChatSideBar/ChatItem/ChatItem.module.css
  client/src/components/study/ChatSideBar/ChatList/ChatList.jsx
  client/src/components/study/ChatSideBar/ChatList/ChatList.module.css
  client/src/components/study/ChatSideBar/ChatSideBar.jsx
  client/src/components/study/ChatSideBar/ChatSideBar.module.css
Labels: 🎂FEAT

#182 [FE] Bookmark, TotalParticipant 컴포넌트 리팩토링
  client/package-lock.json
  client/src/api/auth-api.js
  client/src/components/commons/UserCount/UserCount.jsx
  client/src/components/commons/UserCount/UserCount.module.css
  client/src/components/home/Bookmark/Bookmark.jsx
  client/src/components/home/Bookmark/Bookmark.module.css
  client/src/components/home/FeedGrid/FeedGrid.jsx
  client/src/components/home/Header/Header.jsx
  client/src/components/home/StudyRoomCard/StudyRoomCard.jsx
  client/src/components/home/StudyRoomFeed/StudyRoomFeed.jsx
  client/src/components/home/TotalParticipant/TotalParticipant.jsx
  client/src/components/home/TotalParticipant/TotalParticipant.module.css
  client/src/components/home/UserList/UserList.jsx
  client/src/components/home/UserList/UserList.module.css
  client/src/components/home/index.js
  client/src/pages/Login/RedirectPage.jsx
  client/src/pages/LogoutRedirectPage/LogoutRedirectPage.jsx
  client/src/pages/MainHome/MainHome.jsx
  client/src/recoil/user-state.js
Labels: ♻️REFAC

#186 [FE] 모달 관련 수정
  client/src/components/commons/Dropdown/Dropdown.jsx
  client/src/components/commons/Modal/Modal.jsx
  client/src/components/commons/Modal/Modal.module.css
  client/src/components/commons/Modal/NicknameEditModal.jsx
  client/src/components/commons/Modal/NicknameEditModal.module.css
  client/src/components/commons/Modal/PasswordModal.jsx
  client/src/components/home/Bookmark/Bookmark.jsx
  client/src/components/home/Header/Header.jsx
  client/src/components/home/StudyRoomCard/StudyRoomCard.jsx
  client/src/components/mypage/AccountDeleteModal/AccountDeleteModal.jsx
  client/src/components/study/Plans/Plan.jsx
  client/src/components/study/Plans/Plan.module.css
  client/src/hooks/useModal.js
  client/src/hooks/useOutSideClick.js
  client/src/pages/CreateRoom.jsx
  client/src/pages/ErrorPage/ErrorPage.jsx
  client/src/pages/JoinRoom.jsx
  client/src/pages/MyPage/MyPage.jsx
  client/src/pages/StudyRoom/StudyRoom.jsx
Labels: ♻️REFAC

#187 [FE] 스터디 관련 컴포넌트 리팩토링
  client/src/api/openvidu-api.js
  client/src/components/commons/Dropdown/Dropdown.module.css
  client/src/components/study/ChatSideBar/ChatList/ChatList.module.css
  client/src/components/study/ParticipantSideBar/ParticipantSideBar.jsx
  client/src/components/study/SettingBar/SettingBar.jsx
  client/src/components/study/SettingBar/SettingBar.module.css
  client/src/components/study/SettingRoom/SettingRoom.jsx
  client/src/components/study/SettingRoom/SettingRoom.module.css
  client/src/components/study/SettingSideBar/SettingSideBar.jsx
  client/src/components/study/SettingSideBar/SettingSideBar.module.css
  client/src/components/study/StudyBar/StudyBar.jsx
  client/src/components/study/StudyBar/StudyBar.module.css
  client/src/components/study/UserTag/UserTag.jsx
  client/src/components/study/UserVideo/UserVideo.jsx
  client/src/components/study/UserVideo/UserVideo.module.css
  client/src/hooks/commons/useAsync.js
  client/src/hooks/index.js
  client/src/hooks/study/useManageLocalUser.js
  client/src/hooks/study/useManageRemoteUsers.js
  client/src/hooks/study/useMyStream.js
  client/src/hooks/study/useToggleSideBar.js
  client/src/index.css
  client/src/pages/CreateRoom.jsx
  client/src/pages/JoinRoom.jsx
  client/src/pages/MyPage/MyPage.jsx
  client/src/pages/StudyRoom/StudyRoom.jsx
  client/src/pages/StudyRoom/StudyRoom.module.css
  client/src/recoil/studyroom-state.js
Labels: ♻️REFAC

#191 [BE] study room
  server/src/main/java/com/oddok/server/domain/bookmark/application/BookmarkService.java
  server/src/main/java/com/oddok/server/domain/profile/application/ProfileService.java
  server/src/main/java/com/oddok/server/domain/studyroom/application/StudyRoomService.java
  server/src/main/java/com/oddok/server/domain/user/api/UserController.java
Labels: 🐛FIX

#192 [FE] auth 리팩토링
  client/src/App.jsx
  client/src/App.module.css
  client/src/api/auth-api.js
  client/src/api/auth/auth-api.js
  client/src/api/auth/kakao.js
  client/src/api/axios-config.js
  client/src/api/error/ApiError.js
  client/src/api/error/AuthError.js
  client/src/api/error/LoginError.js
  client/src/api/error/OpenviduError.js
  client/src/api/error/StudyRoomError.js
  client/src/api/study-room-api.js
  client/src/components/commons/ErrorModal/ErrorModal.jsx
  client/src/components/commons/Loading/Loading.module.css
  client/src/components/commons/Modal/Modal.jsx
  client/src/components/home/Bookmark/Bookmark.jsx
  client/src/components/home/Bookmark/Bookmark.module.css
  client/src/components/home/Header/Header.jsx
  client/src/components/mypage/AccountDeleteModal/AccountDeleteModal.jsx
  client/src/hooks/useAsync.js
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/Login.module.css
  client/src/pages/Login/RedirectPage.jsx
  client/src/pages/LogoutRedirectPage/LogoutRedirectPage.jsx
  client/src/pages/MainHome/MainHome.jsx
  client/src/utils/constants/API_ERROR.js
Labels: ♻️REFAC

#193 [FE] 스터디룸 검색 로직 변경
  client/src/api/study-room-api.js
  client/src/components/commons/Thumbnail/Thumbnail.jsx
  client/src/components/commons/Thumbnail/Thumbnail.module.css
  client/src/components/commons/UserCount/UserCount.module.css
  client/src/components/home/FeedGrid/FeedGrid.jsx
  client/src/components/home/FeedGrid/FeedGrid.module.css
  client/src/components/home/StudyRoomCard/StudyRoomCard.jsx
  client/src/components/home/StudyRoomCard/StudyRoomCard.module.css
  client/src/components/home/StudyRoomFeed/StudyRoomFeed.jsx
  client/src/components/home/StudyRoomFeed/StudyRoomFeed.module.css
  client/src/components/home/TabMenu/TabMenu.jsx
  client/src/components/search/HashtagList/HashtagList.jsx
  client/src/components/search/InputForm/InputForm.jsx
  client/src/components/search/InputForm/InputForm.module.css
  client/src/components/search/SearchBrowse/SearchBrowse.jsx
  client/src/components/search/SearchBrowse/SearchBrowse.module.css
  client/src/components/search/SearchHistory/SearchHistory.jsx
  client/src/components/search/SearchHistory/SearchHistory.module.css
  client/src/components/search/SearchResult/SearchResult.jsx
  client/src/components/search/SearchResult/SearchResult.module.css
  client/src/components/search/index.js
  client/src/hooks/index.js
  client/src/hooks/search/useSearchHistory.js
  client/src/hooks/useSearchParams.js
  client/src/pages/Search/Search.jsx
  client/src/pages/Search/Search.module.css
  client/src/utils/index.js
  client/src/utils/parseQueryString.js
Labels: ♻️REFAC

#198 [FE] 마이페이지 스크롤 메뉴 구현 및 리팩토링
  client/src/components/commons/Textarea/Textarea.module.css
  client/src/components/mypage/DatePicker/CustomInput.module.css
  client/src/components/mypage/DatePicker/DatePicker.jsx
  client/src/components/mypage/DatePicker/DatePicker.module.css
  client/src/components/mypage/MyAccount/MyAccount.jsx
  client/src/components/mypage/MyAccount/MyAccount.module.css
  client/src/components/mypage/MyGoal/MyGoal.module.css
  client/src/components/mypage/MyGoalEditModal/MyGoalEditModal.jsx
  client/src/components/mypage/MyGoalEditModal/MyGoalEditModal.module.css
  client/src/components/mypage/MyRoom/MyRoom.jsx
  client/src/components/mypage/MyRoom/MyRoom.module.css
  client/src/components/mypage/MyRoomEditModal/MyRoomEditModal.jsx
  client/src/components/mypage/MyRoomEditModal/MyRoomEditModal.module.css
  client/src/components/mypage/Room/Room.jsx
  client/src/components/mypage/Room/Room.module.css
  client/src/components/mypage/SideNavBar/SideNavBar.jsx
  client/src/components/mypage/SideNavBar/SideNavBar.module.css
  client/src/components/mypage/StudyTime/StudyTime.jsx
  client/src/components/mypage/StudyTime/StudyTime.module.css
  client/src/components/mypage/TimeRecordList/TimeRecordList.jsx
  client/src/components/mypage/TimeRecordList/TimeRecordList.module.css
  client/src/components/mypage/TimeTable/TimeRecordBlock/TimeRecordBlock.jsx
  client/src/components/mypage/TimeTable/TimeTable.jsx
  client/src/components/mypage/TimeTable/TimeTable.module.css
  client/src/components/mypage/TimeTable/TimeTableGrid/TimeTableGrid.jsx
  client/src/components/mypage/TimeTable/TimeTableGrid/TimeTableGrid.module.css
  client/src/components/mypage/index.js
  client/src/index.css
  client/src/pages/MyPage/MyPage.jsx
  client/src/pages/MyPage/MyPage.module.css
  client/src/utils/getTimeDiff.js
  client/src/utils/index.js
Labels: 🎂FEAT, ♻️REFAC
